// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	TaskComplete(ctx context.Context, id int64) (Task, error)
	TaskFail(ctx context.Context, arg TaskFailParams) (Task, error)
	TaskInsert(ctx context.Context, arg TaskInsertParams) (Task, error)
	TaskListAvailable(ctx context.Context, arg TaskListAvailableParams) ([]Task, error)
	TaskRetry(ctx context.Context, arg TaskRetryParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
