// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: task.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const taskComplete = `-- name: TaskComplete :exec
WITH locked_task AS (
  SELECT id
  FROM task
  WHERE id = $1::bigint 
  FOR UPDATE
),
updated_task AS (
  UPDATE task
  SET
    state = 'completed'::task_state,
    ended_at = now()
  FROM locked_task
  WHERE task.id = locked_task.id AND task.state = 'running'
  RETURNING task.id, task.state, task.attempt, task.attempted_at, task.created_at, task.ended_at, task.scheduled_at, task.priority, task.payload, task.error, task.kind, task.queue
)
SELECT id, state, attempt, attempted_at, created_at, ended_at, scheduled_at, priority, payload, error, kind, queue FROM updated_task
`

func (q *Queries) TaskComplete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, taskComplete, id)
	return err
}

const taskFail = `-- name: TaskFail :exec
WITH locked_task AS (
  SELECT id
  FROM task
  WHERE id = $1::bigint 
  FOR UPDATE
),
updated_task AS (
  UPDATE task
  SET
    state = 'failed'::task_state,
    error = $2::text,
    ended_at = now()
  FROM locked_task
  WHERE task.id = locked_task.id AND task.state = 'running'
  RETURNING task.id, task.state, task.attempt, task.attempted_at, task.created_at, task.ended_at, task.scheduled_at, task.priority, task.payload, task.error, task.kind, task.queue
)
SELECT id, state, attempt, attempted_at, created_at, ended_at, scheduled_at, priority, payload, error, kind, queue FROM updated_task
`

type TaskFailParams struct {
	ID  int64
	Err string
}

func (q *Queries) TaskFail(ctx context.Context, arg TaskFailParams) error {
	_, err := q.db.Exec(ctx, taskFail, arg.ID, arg.Err)
	return err
}

const taskInsert = `-- name: TaskInsert :exec
INSERT INTO task(
    state,
    payload,
    kind,
    priority,
    queue
) VALUES (
    'available'::task_state,
    $1::jsonb,
    $2::text,
    $3::int,
    $4::text
) RETURNING id, state, attempt, attempted_at, created_at, ended_at, scheduled_at, priority, payload, error, kind, queue
`

type TaskInsertParams struct {
	Payload  []byte
	Kind     string
	Priority int32
	Queue    string
}

func (q *Queries) TaskInsert(ctx context.Context, arg TaskInsertParams) error {
	_, err := q.db.Exec(ctx, taskInsert,
		arg.Payload,
		arg.Kind,
		arg.Priority,
		arg.Queue,
	)
	return err
}

const taskListAvailable = `-- name: TaskListAvailable :many
WITH
  locked_tasks AS (
    SELECT id, state, attempt, attempted_at, created_at, ended_at, scheduled_at, priority, payload, error, kind, queue
    FROM task
    WHERE
      state = 'available'
      AND queue = $1::text
      AND scheduled_at <= now()
    ORDER BY
      priority ASC,
      scheduled_at ASC,
      id ASC
    LIMIT $2::integer
    FOR UPDATE SKIP LOCKED
  )
UPDATE task
SET
  state = 'running',
  attempt = task.attempt + 1,
  attempted_at = now()
FROM locked_tasks
WHERE task.id = locked_tasks.id
RETURNING task.id, task.state, task.attempt, task.attempted_at, task.created_at, task.ended_at, task.scheduled_at, task.priority, task.payload, task.error, task.kind, task.queue
`

type TaskListAvailableParams struct {
	Queue string
	Max   int32
}

func (q *Queries) TaskListAvailable(ctx context.Context, arg TaskListAvailableParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, taskListAvailable, arg.Queue, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.Attempt,
			&i.AttemptedAt,
			&i.CreatedAt,
			&i.EndedAt,
			&i.ScheduledAt,
			&i.Priority,
			&i.Payload,
			&i.Error,
			&i.Kind,
			&i.Queue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskRetry = `-- name: TaskRetry :exec
WITH locked_task AS (
  SELECT id
  FROM task
  WHERE id = $1::bigint 
  FOR UPDATE
),
updated_task AS (
  UPDATE task
  SET
    state = 'available'::task_state,
    error = $2::text,
    scheduled_at = $3::timestamptz
  FROM locked_task
  WHERE task.id = locked_task.id AND task.state = 'running'
  RETURNING task.id, task.state, task.attempt, task.attempted_at, task.created_at, task.ended_at, task.scheduled_at, task.priority, task.payload, task.error, task.kind, task.queue
)
SELECT id, state, attempt, attempted_at, created_at, ended_at, scheduled_at, priority, payload, error, kind, queue FROM updated_task
`

type TaskRetryParams struct {
	ID          int64
	Err         string
	Scheduledat pgtype.Timestamptz
}

func (q *Queries) TaskRetry(ctx context.Context, arg TaskRetryParams) error {
	_, err := q.db.Exec(ctx, taskRetry, arg.ID, arg.Err, arg.Scheduledat)
	return err
}
